config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  #get 'home/index'
  get 'home/about'
  root 'friends#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, exept: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

def correct_user
  @friend = current_user.friends.find_by(id: params[:id])
  redirect_to friends_path, notice: "Not Authorised To Edit This Friend" if @friend.nil?
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
    @about_me = "My Name is Josh Man"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :first_name, class:"form-control", placeholder: "First Name" %>
  </div><br/>

  <div class="field form-group">
    <%= form.text_field :last_name, class:"form-control", placeholder: "Last Name" %>
  </div><br/>

  <div class="field form-group">
    <%= form.text_field :email, class:"form-control", placeholder: "Email" %>
  </div><br/>

  <div class="field form-group">
    <%= form.text_field :phone, class:"form-control", placeholder: "Phone" %>
  </div><br/>

  <div class="field form-group">
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div><br/>

  <div>
    <%= form.submit class:"btn btn-success" %>
  </div>

<% end %>

app/views/friends/_friend.html.erb
<div class="card" style="width: 18rem;">
    <h5 class="card-title">
      <%= friend.first_name %>
      <%= friend.last_name %>
      </h5>
    <p class="card-text">
      <%= friend.email %>
      <br/>
      <%= friend.phone %>
      </p>
    <%= button_to "Destroy this friend", @friend, method: :delete, class:"btn btn-danger", style:"width: 18rem;" %>
    <br/>
    <%= link_to "Edit this friend", edit_friend_path(@friend), class:"btn btn-secondary" %>
    <br/>
    <%= link_to "Back to friends", friends_path, class:"btn btn-dark" %>
  </div>
</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>
<br/>
<%= render "form", friend: @friend %>
<br/>
<div>
  <%= link_to "Show this friend", @friend, class:"btn btn-secondary" %>
  <%= link_to 'Delete', @friend, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  <%= link_to "Back to friends", friends_path, class:"btn btn-dark" %>
</div>

app/views/friends/index.html.erb
<% if user_signed_in? %>

  <table class="table table-striped">
    <thead class="thread-dark">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
      <% @friends.each do |friend| %>
        <% if friend.user == current_user %>
          <tr>
            <td><%= link_to friend.first_name + ' ' + friend.last_name, friend %> </td>
            <td><%= friend.email %></td>
            <td><%= friend.phone %></td>

            <td><%= link_to 'Edit',edit_friend_path(friend), class: "btn btn-outline-secondary btn-small" %></td>
            <td><%= link_to 'Delete', friend, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-small" %></td>
          </tr>
        <% end %>  
      <% end %>
    </tbody>
  </table>

  <%= link_to "+ New friend", new_friend_path, class:"btn btn-success" %>

<% else %>
  <h1>Привет, Амелия!</h1>
  <p>Это первый сайт, который мы сделали вместе!</p>
<% end %>

app/views/friends/new.html.erb
<h1>Add New friend</h1>
<br/>
<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back", friends_path, class:"btn btn-dark" %>
</div>

app/views/friends/show.html.erb
<%= render @friend %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-dark">
  <div class="container-fluid">
  	<%= link_to 'Friend App', root_path, class:"navbar-brand" %>
   
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      
      <ul class="navbar-nav">

          <li class="nav-item">
          	<%= link_to "О Нас", home_about_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
          	<%= link_to "Добавить друга", new_friend_path, class:"nav-link" %>
          </li>

        <% if user_signed_in? %>

          <li class="nav-item">
            <%= link_to "Редактировать профайл", edit_user_registration_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Добавить друга", new_friend_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
          
        <% else %>

          <li class="nav-item">
        	 <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
          	<%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us </h1>
	<p>
		<%= @about_me %>
	</p>

app/views/home/index.html.erb
<h1>Привет, Амелия!</h1>
<p>Это первый сайт, который мы сделали вместе!</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Friends app</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>

    <%= render 'home/header' %>
    <div class="conteiner">
    <br/>
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
    <div class="mx-5"> 
      <%= yield %>
    </div>  
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
</html>